### ISSUE TITLE
Problem: common.soa.billing_service.exceptions.BillingServiceError

### ISSUE THREAD

**Issue by trinitychristiana-eb** [trinitychristiana-eb/task-tracker#69]
### I get this error whenever I try to access a dashboard to an event I created in evbdev

```zsh
common.soa.billing_service.exceptions.BillingServiceError
BillingServiceError: action `get_payout_schedule`: SERVER_ERROR (Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/service/job.py", line 878, in run
    action.run(self, controller, idx)
  File "/usr/local/lib/python2.7/dist-packages/billing_service/actions/schedules/get_payout_schedule.py", line 44, in run
    self.event_payout_schedule = get_schedule_for_events(event_ids=self.event_ids)
  File "/usr/local/lib/python2.7/dist-packages/billing_service/backends/scheduler/helpers.py", line 244, in get_schedule_for_events
    billing_settings = get_effective_event_billing_settings(event_ids)
  File "/usr/local/lib/python2.7/dist-packages/billing_service/backends/billing_settings/helpers.py", line 457, in get_effective_event_billing_settings
    user_billing_settings_by_id = get_billing_settings_for_users(user_ids)
  File "/usr/local/lib/python2.7/dist-packages/billing_service/backends/billing_settings/helpers.py", line 130, in get_billing_settings_for_users
    user_billing_settings = get_user_billing_settings(user_ids=user_ids)
  File "/usr/local/lib/python2.7/dist-packages/billing_service/models/billing_settings.py", line 129, in get_user_billing_settings
    for record in billing_settings:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/core/django/src/www/eventbrite/common/db/backends/mysql/base.py", line 159, in execute
    return self._instrument_call(f, sql, args)
  File "/srv/core/django/src/www/eventbrite/common/db/backends/mysql/base.py", line 146, in _instrument_call
    res = function(sql, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_mysql/monkey_patches.py", line 35, in execute
    return orig_execute(self, sql, args)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'Billing_Settings_User.is_platinum' in 'field list'")
)
action `check_event_payout_eligibility`: ACTION_NOT_PROCESSED
action `get_billing_settings`: ACTION_NOT_PROCESSED
```

**Comment by trintiychristiana-eb** [comment]
Found a solution to the billing problem when trying to go to the event dashboard to an event I created. But I will need to pull down the billing repo.
https://eventbrite.slack.com/archives/C02A1QW24/p1596072966065400?thread_ts=1595636068.037400&cid=C02A1QW24
